<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Coordinated Universal Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0" os="" host="WIN-8P12VIF73T3"><DocLocation><![CDATA[C:\Users\uftuser\repos\spencer\octanedemouft\AOS]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AOS]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[SearchASpeaker]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:43]]></Time>
<TimeTick>1584281143</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:43]]></Time>
<TimeTick>1584281143</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SpeakersCategoryTxt.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:43]]></Time>
<TimeTick>1584281143</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[SpeakersCategoryTxt.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HOME.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:45]]></Time>
<TimeTick>1584281145</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[HOME.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[menuSearch.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:45]]></Time>
<TimeTick>1584281145</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[menuSearch.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Search AdvantageOnlineShopping.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["speaker"]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:45]]></Time>
<TimeTick>1584281145</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[Search AdvantageOnlineShopping.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Search AdvantageOnlineShopping.Submit]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:45]]></Time>
<TimeTick>1584281145</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[Search AdvantageOnlineShopping.Submit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:46]]></Time>
<TimeTick>1584281146</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[$269.99.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:46]]></Time>
<TimeTick>1584281146</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[$269.99.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HOME.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[HOME.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" Source="SearchASpeaker" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/15/2020 - 14:05:42" eTime="3/15/2020 - 14:05:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[SearchASpeaker Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[CheckOut]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[ShoppingCart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="49" Source="CheckOut" SourceLine="-1" >
<Disp><![CDATA[ShoppingCart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[check_out_btn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="CheckOut" SourceLine="-1" >
<Disp><![CDATA[check_out_btn.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" Source="CheckOut" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="47" Source="CheckOut" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/15/2020 - 14:05:47" eTime="3/15/2020 - 14:05:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="44" >
<Disp><![CDATA[CheckOut Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T21">
<AName><![CDATA[RemoveItem]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[ShoppingCart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" Source="RemoveItem" SourceLine="-1" >
<Disp><![CDATA[ShoppingCart.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[REMOVE.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="62" Source="RemoveItem" SourceLine="-1" >
<Disp><![CDATA[REMOVE.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Link.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/15/2020 - 14:05:47]]></Time>
<TimeTick>1584281147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="65" Source="RemoveItem" SourceLine="-1" >
<Disp><![CDATA[Link.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" Source="RemoveItem" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="57" Source="RemoveItem" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/15/2020 - 14:05:47" eTime="3/15/2020 - 14:05:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="54" >
<Disp><![CDATA[RemoveItem Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[AOS Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="3/15/2020 - 14:05:38" eTime="3/15/2020 - 14:05:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test AOS Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>